//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeDocs.Generator {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class ExampleTemplate : ExampleTemplateBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 6 ""
            this.Write("\n\n\n\n    ");
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(" public ");
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(CoreType));
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(" :");
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(".I");
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write("public, IDisposable\n    {\n        // Checking: static field, instance field, cons" +
                    "tant, enum, static property, instance property, static method, instance method, " +
                    "delegate, event\n\n");
            
            #line default
            #line hidden
            
            #line 14 ""
foreach(var accessor in Accessors){
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(" static bool ");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write("StaticField = true;\n        ");
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write(" bool ");
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write("Field;\n        ");
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write(" const bool ");
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write("Const = true;\n        ");
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write(" enum ");
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write("Enum \n        {\n            ");
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write("EnumValue\n        };\n        ");
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(" static bool ");
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write("StaticProperty => true;\n        ");
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(" bool ");
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write("Property => true;\n        ");
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(" static bool ");
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write("StaticMethod() => true;\n        ");
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write(" bool ");
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write("Method() => true;\n        ");
            
            #line default
            #line hidden
            
            #line 26 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 26 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 26 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 26 ""
            this.Write(" delegate bool ");
            
            #line default
            #line hidden
            
            #line 26 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 26 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 26 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 26 ""
            this.Write("Delegate();\n        ");
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(" event ");
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write("Delegate ");
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write("Event;\n                                \n");
            
            #line default
            #line hidden
            
            #line 29 ""
}
            
            #line default
            #line hidden
            
            #line 30 ""
            this.Write("    \n\n        ");
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(" public static ");
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(" operator+ (");
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(" a, ");
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(" b) => a;\n        \n        // Indexers\n        \n        ");
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 36 ""
            this.Write(" public bool this[int x] => true;\n        \n        // Constructors\n");
            
            #line default
            #line hidden
            
            #line 39 ""
if(CoreType=="class"){
            
            #line default
            #line hidden
            
            #line 40 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 40 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 40 ""
            this.Write(" public ");
            
            #line default
            #line hidden
            
            #line 40 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 40 ""
            this.Write("() { }\n");
            
            #line default
            #line hidden
            
            #line 41 ""
}
            
            #line default
            #line hidden
            
            #line 42 ""
            this.Write("        \n        \n");
            
            #line default
            #line hidden
            
            #line 44 ""
foreach(var accessor in Accessors){
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(ConstructorArgs()));
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write("){\n");
            
            #line default
            #line hidden
            
            #line 46 ""
foreach(var a2 in Accessors){
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(a2));
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write("Field = true;\n            ");
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(a2));
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write("Event = null;\n");
            
            #line default
            #line hidden
            
            #line 49 ""
}
            
            #line default
            #line hidden
            
            #line 50 ""
            this.Write("        }\n");
            
            #line default
            #line hidden
            
            #line 51 ""
}
            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write("  \n        \n        \n        // Finalizers & Disposable\n\n        ");
            
            #line default
            #line hidden
            
            #line 57 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 57 ""
            this.Write(" public void Dispose() { return; }\n        \n");
            
            #line default
            #line hidden
            
            #line 59 ""
if(CoreType=="class"){
            
            #line default
            #line hidden
            
            #line 60 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 60 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 60 ""
            this.Write(" ~");
            
            #line default
            #line hidden
            
            #line 60 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 60 ""
            this.Write("() { Dispose(); }\n");
            
            #line default
            #line hidden
            
            #line 61 ""
}
            
            #line default
            #line hidden
            
            #line 62 ""
            this.Write("        \n#region Interfaces\n\n");
            
            #line default
            #line hidden
            
            #line 65 ""
foreach(var accessor in Accessors){
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write(" interface I");
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 66 ""
            this.Write("\n    {\n        ");
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write(" bool ");
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 68 ""
            this.Write("Property {get;}\n        ");
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Doc));
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write(" bool ");
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write("_");
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write("Method();\n    \n    }\n");
            
            #line default
            #line hidden
            
            #line 72 ""
}
            
            #line default
            #line hidden
            
            #line 73 ""
            this.Write("        \n\n#endregion\n\n        // Nested Types\n    #region Nested Types\n    \n");
            
            #line default
            #line hidden
            
            #line 80 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(NestedType));
            
            #line default
            #line hidden
            
            #line 80 ""
            this.Write("\n    \n    #endregion\n    }\n    \n    \n    ");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class ExampleTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
